env:
  browser: true
  es6: true
  node: true
extends: 
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:react/jsx-runtime'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - react-hooks
  - import
rules: 
  semi:
    - error
    - always
  react-hooks/rules-of-hooks:
    - error
  react-hooks/exhaustive-deps:
    - warn
  no-console: 0
  no-inline-comments: 0
  eqeqeq: 2
